development:
  MAPBOX_TOKEN: "pk.eyJ1Ijoiam9obm55bGluIiwiYSI6ImNqbnFid3k5cTFubzQza21xZHV0cWQ1cnoifQ.76oS4KVM4ODx8aOPldY4VQ"
  SESSION_SECRET: "sdu9ihwds89i3"

test:
  MAPBOX_TOKEN: "pk.eyJ1Ijoiam9obm55bGluIiwiYSI6ImNqbnFid3k5cTFubzQza21xZHV0cWQ1cnoifQ.76oS4KVM4ODx8aOPldY4VQ"
  SESSION_SECRET: "sdu9ihwds89i3"

production:
  MAPBOX_TOKEN: "pk.eyJ1Ijoiam9obm55bGluIiwiYSI6ImNqbnFid3k5cTFubzQza21xZHV0cWQ1cnoifQ.76oS4KVM4ODx8aOPldY4VQ"
  SESSION_SECRET: "sdu9ihwds89i3"
