development:
  MAPBOX_TOKEN: <token to access Mapbox APIs>
  SESSION_SECRET: <some secret>

test:
  MAPBOX_TOKEN: <token to access Mapbox APIs>
  SESSION_SECRET: <some secret>

production:
  MAPBOX_TOKEN: <token to access Mapbox APIs>
  SESSION_SECRET: <some secret>
