development:
  GOOGLE_CLOUD_KEY: <key to access Google web APIs>
  MAPBOX_TOKEN: <token to access Mapbox APIs>

test:
  GOOGLE_CLOUD_KEY: <key to access Google web APIs>
  MAPBOX_TOKEN: <token to access Mapbox APIs>
