development:
  GOOGLE_CLOUD_KEY: "AIzaSyAD656N9isRF8t11FeFUvizKJCTB07Vrqo"
  MAPBOX_TOKEN: "pk.eyJ1Ijoiam9obm55bGluIiwiYSI6ImNqbnFid3k5cTFubzQza21xZHV0cWQ1cnoifQ.76oS4KVM4ODx8aOPldY4VQ"
  SESSION_SECRET: "sdu9ihwds89i3"

test:
  GOOGLE_CLOUD_KEY: "AIzaSyAD656N9isRF8t11FeFUvizKJCTB07Vrqo"
  MAPBOX_TOKEN: "pk.eyJ1Ijoiam9obm55bGluIiwiYSI6ImNqbnFid3k5cTFubzQza21xZHV0cWQ1cnoifQ.76oS4KVM4ODx8aOPldY4VQ"
  SESSION_SECRET: "sdu9ihwds89i3"

production:
  GOOGLE_CLOUD_KEY: "AIzaSyAD656N9isRF8t11FeFUvizKJCTB07Vrqo"
  MAPBOX_TOKEN: "pk.eyJ1Ijoiam9obm55bGluIiwiYSI6ImNqbnFid3k5cTFubzQza21xZHV0cWQ1cnoifQ.76oS4KVM4ODx8aOPldY4VQ"
  SESSION_SECRET: "sdu9ihwds89i3"
